apiVersion: v1
kind: Service
metadata:
  name: ic-biller-experience-api
  labels:
    app: ic-biller-experience-api
spec:
  type: ClusterIP
  selector:
    app: ic-biller-experience-api
  ports:
    - name: http
      port: 8080
      targetPort: http
