export interface ExperienceAction { id: string; label: string; action: number | string; variant: string }
export interface ExperiencePreferences { guest_checkout_allowed: boolean; offer_autopay: boolean; enroll_during_payment: boolean; offer_paperless: boolean; reminder_channel: number | string; accepted_methods: string[]; self_service_history: boolean; self_service_updates: boolean; fee_handling: number | string; preview: { default_device: string; enabled_scenarios: string[] }; recommendation_rationale?: Record<string,string> }
export interface BillingPresentationCategory { id: string; display_name: string; cadence?: string | number | null; cadence_label: string; state_summary: string; payment_mode?: string | number | null; maximum_installments?: number | null }
export interface ExperienceDefinition { schema_version: string; biller_id: string; brand: { display_name: string; primary_color: string; secondary_color: string; font_family: string | null }; content: { heading: string; introduction: string; support_text: string; privacy_policy_url: string; terms_of_service_url: string }; pwa: { name: string; short_name: string; theme_color: string; background_color: string }; enabled_payment_capabilities: string[]; ui?: { layout: string; theme: { density: string; radius: string; surface: string }; sections: Array<{ id: string; type: string; variant: string; visible: boolean }>; actions: ExperienceAction[] }; preferences?: ExperiencePreferences; billing?: { categories: BillingPresentationCategory[] } }
export interface Invoice { id: string; accountNumber: string; payerName: string; amountCents: number; dueDate: string; description: string; status: string }
export type PaymentMethod = 'card' | 'ach';
export interface PaymentRequest { invoiceId: string; method: PaymentMethod; autoPay: boolean; paperless: boolean; scheduledFor?: string; payerName?: string; payerEmail?: string; accountNumber: string; idempotencyKey: string }
export interface PaymentReceipt { confirmation: string; amountCents: number; feeCents: number; totalCents: number; status?: string; scheduledFor?: string; payerAccountId?: string; preferenceUpdateFailed?: boolean }
export interface PayerProfile { payer_id: string; biller_id: string; name: string; email: string; account_numbers: string[]; preferences: { autopay: boolean; paperless: boolean; channels: Array<'email'|'sms'>; payment_day: number|null } }
export interface PaymentHistory { payment_id: string; invoice_id: string; amount_cents: number; fee_cents: number; total_cents: number; confirmation: string; status: string; created_at: string }
