import { FormEvent, useEffect, useMemo, useState } from 'react';
import { DemoPaymentExperienceProvider } from './provider';
import { logError, logEvent, observed } from './telemetry';
import type { ExperienceDefinition, Invoice, PaymentReceipt } from './types';

const provider = new DemoPaymentExperienceProvider();
type Step = 'lookup' | 'method' | 'review' | 'complete';

export function App() {
  const [config, setConfig] = useState<ExperienceDefinition>(); const [invoice, setInvoice] = useState<Invoice>(); const [step, setStep] = useState<Step>('lookup');
  const [method, setMethod] = useState<'card'|'ach'>('card'); const [autoPay, setAutoPay] = useState(false); const [paperless, setPaperless] = useState(false); const [receipt, setReceipt] = useState<PaymentReceipt>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { const slug = billerSlug(); const configUrl = import.meta.env.VITE_CONFIG_URL ?? `/api/public/experiences/${encodeURIComponent(slug)}`; const manifest = document.querySelector<HTMLLinkElement>('#experience-manifest'); if (manifest) manifest.href = `/api/public/experiences/${encodeURIComponent(slug)}/manifest.webmanifest`; observed('pwa.config.load', async () => { const response = await fetch(configUrl, { cache: 'no-store' }); if (!response.ok) throw new Error('Experience configuration is unavailable.'); return response.json() as Promise<ExperienceDefinition>; }).then(value => { setConfig(value); document.title = value.pwa.name; document.documentElement.style.setProperty('--brand', value.brand.primary_color); }).catch(caught => { setError(toMessage(caught)); logError('pwa.config.failed', caught, { biller_slug: slug }); }); }, []);
  const fee = useMemo(() => method === 'card' ? 250 : 95, [method]);
  async function lookup(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); try { const data = new FormData(event.currentTarget); setInvoice(await provider.getInvoice(String(data.get('account')))); setStep('method'); } catch (caught) { setError(toMessage(caught)); } finally { setBusy(false); } }
  async function pay() { if (!invoice) return; setBusy(true); setError(''); try { setReceipt(await provider.pay({ invoiceId: invoice.id, method, autoPay, paperless })); setStep('complete'); logEvent('pwa.payment.completed', { method, autopay_opt_in: autoPay, paperless_opt_in: paperless }); } catch (caught) { setError(toMessage(caught)); } finally { setBusy(false); } }
  if (!config) return <main className="center"><div className="card" aria-live="polite">{error || 'Loading your payment experience…'}</div></main>;
  return <div className="app"><header style={{background:config.brand.primary_color}}><div className="mark">{initials(config.brand.display_name)}</div><strong>{config.brand.display_name}</strong><span>Secure payment</span></header><main><div className="intro"><p>Account services</p><h1>{config.content.heading}</h1><span>{config.content.introduction}</span></div>{error && <div className="alert" role="alert">{error}</div>}
    {step==='lookup' && <form className="card" onSubmit={lookup}><h2>Find your bill</h2><label>Account number<input name="account" required defaultValue="4421" autoComplete="off" /></label><button disabled={busy}>{busy?'Finding bill…':'Continue'}</button></form>}
    {step==='method' && invoice && <section className="card"><Bill invoice={invoice}/><h2>Choose how to pay</h2><div className="choices">{config.enabled_payment_capabilities.includes('card')&&<button className={method==='card'?'selected':'option'} onClick={()=>setMethod('card')}>Card <small>$2.50 fee</small></button>}{config.enabled_payment_capabilities.includes('ach')&&<button className={method==='ach'?'selected':'option'} onClick={()=>setMethod('ach')}>Bank account <small>$0.95 fee</small></button>}</div><fieldset><legend>Optional preferences</legend><label className="check"><input type="checkbox" checked={autoPay} onChange={e=>setAutoPay(e.target.checked)}/><span><strong>Enroll in AutoPay</strong><small>Use this method for future bills. Cancel anytime.</small></span></label><label className="check"><input type="checkbox" checked={paperless} onChange={e=>setPaperless(e.target.checked)}/><span><strong>Switch to paperless billing</strong><small>Receive bills electronically instead of by mail.</small></span></label></fieldset><button onClick={()=>setStep('review')}>Review payment</button></section>}
    {step==='review' && invoice && <section className="card"><h2>Review and confirm</h2><dl><div><dt>Bill amount</dt><dd>{money(invoice.amountCents)}</dd></div><div><dt>Service fee</dt><dd>{money(fee)}</dd></div><div className="total"><dt>Total</dt><dd>{money(invoice.amountCents+fee)}</dd></div></dl>{(autoPay||paperless)&&<div className="notice">You chose: {[autoPay&&'AutoPay',paperless&&'Paperless billing'].filter(Boolean).join(' and ')}.</div>}<p className="consent">Selecting “Pay now” authorizes this one-time demo payment. Optional preferences are recorded separately.</p><div className="actions"><button className="back" onClick={()=>setStep('method')}>Back</button><button disabled={busy} onClick={pay}>{busy?'Processing…':`Pay ${money(invoice.amountCents+fee)}`}</button></div></section>}
    {step==='complete'&&receipt&&<section className="card success" aria-live="polite"><div className="success-icon">✓</div><h2>Payment received</h2><p>Confirmation <strong>{receipt.confirmation}</strong></p><p>{money(receipt.amountCents+receipt.feeCents)} paid using the demo provider.</p>{autoPay&&<span className="pill">AutoPay requested</span>}{paperless&&<span className="pill">Paperless requested</span>}</section>}
  </main><footer><span>{config.content.support_text}</span><nav><a href={config.content.privacy_policy_url}>Privacy</a><a href={config.content.terms_of_service_url}>Terms</a></nav></footer></div>;
}
function Bill({invoice}:{invoice:Invoice}){return <div className="bill"><div><span>{invoice.description}</span><small>Due {new Date(invoice.dueDate).toLocaleDateString()}</small></div><strong>{money(invoice.amountCents)}</strong></div>};
function money(cents:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)} function initials(name:string){return name.split(' ').map(word=>word[0]).slice(0,2).join('')} function toMessage(error:unknown){return error instanceof Error?error.message:'The request failed.'}
function billerSlug(){const match=window.location.pathname.match(/^\/pay\/([^/]+)/);return match?.[1]??import.meta.env.VITE_BILLER_SLUG??'demo'}
